paths:
  base_dir: '/home/yushiran/BYU_Locating_Bacterial_Flagellar_Motors_2025'
  data_dir: 'Datasets/byu-locating-bacterial-flagellar-motors-2025'
  train_csv: 'train_labels.csv'
  train_dir: 'train'
  test_dir: 'test'
  output_dir: 'outputs'
  submission_dir: 'outputs/submissions'
  model_dir: 'models'
  # yolo dir
  yolo_dataset_dir: 'Datasets/yolo_dataset'
  yolo_model_dir: 'src/models/yolo_v8'
  yolo_weights: 'yolo_weights'
  yolo_best_model_dir: 'src/models/yolo_v8/yolo_weights/yolov8_motor_detector_epoch100_batchsize16/weights/best.pt'
  # 3dunet dir
  3dunet_model_dir: 'src/models/3dunet'
  3dunet_dataset_dir: 'Datasets/3dunet_dataset_heatmap'
  3dunet_output_dir: 'outputs/3dunet'


random_seed: 42
#inference parameters
# Define detection and processing parameters
infer_params:
  confidence_threshold: 0.45
  max_detections_per_tomo: 3
  nms_iou_threshold: 0.2
  concentration: 1  # Process a fraction of slices for fast submission